ALTER TYPE "ActivityAction" ADD VALUE 'FAQ_CREATED';
ALTER TYPE "ActivityAction" ADD VALUE 'FAQ_UPDATED';
ALTER TYPE "ActivityAction" ADD VALUE 'FAQ_STATUS_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE 'FAQ_ARCHIVED';
ALTER TYPE "ActivityAction" ADD VALUE 'FAQ_RESTORED';
