import { randomUUID } from 'node:crypto';
import type { NextFunction, Request, Response } from 'express';
import { REQUEST_ID_HEADER } from '@interscale/shared';

/**
 * `Request.id` is typed as `string | number` by pino-http, which owns that
 * declaration. We always assign a string; `getRequestId` narrows it back for
 * consumers so no call site has to repeat the coercion.
 */
export function getRequestId(req: Request): string {
  return String(req.id);
}

/**
 * Attach a correlation id. An inbound header is reused so a value generated by
 * an upstream proxy survives, otherwise we mint one.
 */
export function requestId(req: Request, res: Response, next: NextFunction): void {
  const incoming = req.get(REQUEST_ID_HEADER);
  req.id = incoming && incoming.length <= 128 ? incoming : randomUUID();
  res.setHeader(REQUEST_ID_HEADER, req.id);
  next();
}
